"""modificaciones en modelo de base de datos

Revision ID: 0e4c858b9ddb
Revises: 97a3e8e7b5f3
Create Date: 2026-06-02 17:02:31.280317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4c858b9ddb'
down_revision: Union[str, Sequence[str], None] = '97a3e8e7b5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=18, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Unicode(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Unicode(length=25),
               type_=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=18, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
