"""creacion de db con nuevo ids

Revision ID: 5fbe652d544c
Revises: 
Create Date: 2026-06-20 21:17:10.890360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbe652d544c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.Unicode(length=50), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Unicode(length=10), nullable=False),
    sa.Column('old_value', sa.Unicode(), nullable=True),
    sa.Column('new_value', sa.Unicode(), nullable=True),
    sa.Column('changed_by', sa.Unicode(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('categories',
    sa.Column('category_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('departament', sa.String(length=50), nullable=False),
    sa.Column('cost_center', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('locations',
    sa.Column('location_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Unicode(length=25), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_tag', sa.Unicode(length=20), nullable=False),
    sa.Column('serial_number', sa.Unicode(length=100), nullable=False),
    sa.Column('model', sa.Unicode(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('current_status', sa.Unicode(length=20), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.CheckConstraint("current_status IN ('Disponible', 'Asignado', 'Reparacion', 'Baja')", name='ck_assets_current_status'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_tag')
    )
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=True)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('assignment_date', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('condition_on_return', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('depreciation_schedules',
    sa.Column('depreciation_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('depreciated_value', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('depreciation_id')
    )
    op.create_table('maintenance_logs',
    sa.Column('log_id', sa.String(length=36), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('maintenance_date', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('technician_name', sa.Unicode(length=100), nullable=False),
    sa.Column('cost', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_logs')
    op.drop_table('depreciation_schedules')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('categories')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
