"""creacion de tabla user

Revision ID: 97a3e8e7b5f3
Revises: 680422347335
Create Date: 2026-05-28 17:41:28.955261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a3e8e7b5f3'
down_revision: Union[str, Sequence[str], None] = '680422347335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=18), nullable=False),
    sa.Column('role', sa.Unicode(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.CheckConstraint("role IN ('viewer', 'editor', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
